spring.application.name=Badding_System

spring.datasource.url=jdbc:mysql://localhost:3306/badding_system_db

spring.datasource.username=${YOUR DB USER NAME}

spring.datasource.password=${YOUR DB PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate=debug


spring.mail.host=${YOUR SMPT MAIL}
spring.mail.port=${YOUR SMPT MAIL PORT}
spring.mail.username=${YOUSER NAME}
spring.mail.password=${YOUR PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${YOUR SEND EMAIL }



server.port=9097