spring.application.name=Badding_System

spring.datasource.url=jdbc:mysql://localhost:3306/badding_system_db

spring.datasource.username=root

spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate=debug


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9249cb001@smtp-brevo.com
spring.mail.password=REMOVED
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=satyampatelji9302@gmail.com



server.port=9097